### ISSUE TITLE
Example config?

### ISSUE THREAD

**Issue by w3bn00b** [Teklad/csgo-horker#14]
well, i didnt see this type of aimbot so im just asking for configs?

**Comment by w3bn00b** [comment]
ah and FYI recoil control section is wrong
'''c
Vector diffAngles = HMath::ClampAngle(viewAngle - clampedDir - punchAngle - punchAngle);
```
this looks dirty but works

**Comment by Teklad** [comment]
@w3bnoob Just check config.ini... it gets created/updated every time you run horker.  As a side note... the AimBot doesn't have RCS yet... so that's why it isn't in there like that. :p

@murtuxblux I wouldn't know. It's really up to you whether to learn it or not.  It's a long process in the beginning but you get to where you can create some pretty neat stuff.

**Comment by Teklad** [comment]
A lot of the AimBot code was actually converted over from @ericek111's java-based CSGO hack.  It came in really handy as a reference considering my vector math is really poor.

**Comment by ericek111** [comment]
Yikes, no, don't pls. There's a reason for the AB being disabled ♿♿♿, it's ghetto af and you can get Untrusted for my code (IIRC you're only allowed to change angles 45° per tick). Consider comparing it to some well-known cheats.

**Comment by Teklad** [comment]
@ericek111 I only used it as a reference, lol.  I clamped it down a lot (by default) which should restrict anything crazy.  I did try to use it as-is one good time though.... that didn't go well.  I thought I was spin botting.

The defaults in place actually restrict it to people close to you.  I did notice it doesn't work super great when the sensitivity is to high.... a side effect of using XTest instead of vecViewAngles.

I'm working on digging up vecViewAngles from Engine at the moment.  Digging around in IDA.

**Comment by Teklad** [comment]
I am, however, open to suggestions.... this is my first attempt at writing a hack for... any game? Lol.

**Comment by ericek111** [comment]
There's already viewangles in my cheat.

`
public static String ENGINEPOINTER_SIGNATURE = "48 8B 05 ?? ?? ?? ?? 55 48 89 E5 48 8B 38 48 8B 07";
long foundSplitScreenMgrlea = PatternScanner.getAddressForPattern(Engine.engineModule(), ENGINEPOINTER_SIGNATURE);
long g_SplitScreenMgr = Engine.engineModule().GetAbsoluteAddress(foundSplitScreenMgrlea, 3, 7);
m_dwClientState = Engine.engineModule().readLong(g_SplitScreenMgr);
public static long m_vecViewAngles = 0x8E20;
long viewAnglesPtr = m_dwClientState + m_vecViewAngles;
`

**Comment by Teklad** [comment]
You sure that sig is correct?  I gave that a go and the viewAnglesPtr just returned 0.  I might have misused it, though.

**Comment by ericek111** [comment]
Same here. Hmm. Did you find a new one yet?

**Comment by ericek111** [comment]
You can find both the VA offsets and ClientState by searching "CEngineClient::SetViewAngles:  rejecting invalid value [%f %f %f]\n".

base offset of VA is still 0x8E20.

I'm retarded, I uncommented some old stuff instead of gut quality meme. New sig and dereferencing:
```java
public static String ENGINEPOINTER_SIGNATURE = "48 8B 05 ?? ?? ?? ?? 55 48 8D 3D ?? ?? ?? ?? 48 89 E5 FF 50 28";
long foundSplitScreenMgrlea = PatternScanner.getAddressForPattern(Engine.engineModule(), ENGINEPOINTER_SIGNATURE);
long g_SplitScreenMgr = Engine.engineModule().GetAbsoluteAddress(foundSplitScreenMgrlea, 3, 7);
m_dwClientState = Engine.engineModule().readLong(g_SplitScreenMgr + 8) + 8;
```

**Comment by Teklad** [comment]
Haha.  I've done things like this countless times.  Appreciate the updated signature. :+1:

**Comment by w3bn00b** [comment]
@Teklad well, basically angle - aimPunch * 2 is RCS

**Comment by mrtuxblux** [comment]
@w3bn00b 2 is max RCS right and it can be configured from 0-2?

**Comment by Teklad** [comment]
I think a better idea here would be to add salting (i.e. a certain amount of randomness based on user choice).... when I go to add rcs.  It looks better than an outright static value.

**Comment by mrtuxblux** [comment]
Should header files all have unique names in a project? @Teklad

**Comment by w3bn00b** [comment]
@mrtuxblux 
>  2 is max RCS right and it can be configured from 0-2?
yes but there is no override for * operator so i just used angle - aimpunch - aimpunch

> Should header files all have unique names in a project?
no, if header is in different folder that should not be a problem, but it is still not recommended thing to do

**Comment by Teklad** [comment]
I updated this a bit... now tries to time itself with tick rate for the aim bot to avoid any crazy untrusted issues.... also has a new mode that manipulates camera angle instead of using mouse events for a more consistent experience if you prefer a certain mouse sensitivity.  

This is the default now....  I highly recommend adjusting your aim speed down a bit to compensate for the change.... or re-enable mouse mode by enabling "UseMouseEvents" in config.  Whichever you prefer.

**Comment by Teklad** [comment]
Side note.... I'm not responsible for anyone using any absurd settings for aim speed and getting themselves banned, lol.  The defaults are low-ish on purpose. :p

**Comment by w3bn00b** [comment]
closed
