### ISSUE TITLE
RCS not working at all

### ISSUE THREAD

**Issue by suciuale** [Teklad/csgo-horker#70]
today i discovered that the rcs ain't working at all

**Comment by juhssi3** [comment]
reinstall the chest and try againg

**Comment by suciuale** [comment]
fresh installation

**Comment by suciuale** [comment]
tried with old and new config. same result

**Comment by RealBloodman** [comment]
hmm odd doesn't happen to me :thinking:

**Comment by kusayuzayushko** [comment]
Same issue, my config didn't change

**Comment by kusayuzayushko** [comment]
Somehow it's now fixed, after rebuilding.

**Comment by Teklad** [comment]
Oh right, I fixed the offset just a bit ago for normal RCS.  RCS with aim assist on still worked so that's why it was working for some people but not for others.  I'll close this for now.  I'm gonna have some free time soon to actually get some real work done here.  I apologize for my long hiatus, lol.
