### ISSUE TITLE
Feature Request: RCS and Aimbot

### ISSUE THREAD

**Issue by kazukeno** [Teklad/csgo-horker#9]
A good legit + rage (Casual Rage) aimbot would be nice. It would also be nice with a RCS and it would be good if the RCS and aimbot has changeable values for how they work.

**Comment by Teklad** [comment]
Planned for this weekend (hopefully).

**Comment by Teklad** [comment]
I've got this mostly in place now.  Just need to fix my math so it doesn't act up randomly.  Its.... spinning a bit right now.

**Comment by d1monch1k** [comment]
To make aimbot works on mouse 1, i must change F button to Pointer_Button1 ?

**Comment by Teklad** [comment]
I think?  I've honestly not tested to see if mouse keys work yet.  I was just worried about getting the aimbot working at all.

**Comment by d1monch1k** [comment]
Aim bot is working. Only he watches the opponent through the walls. And with an average distance of almost no

**Comment by Teklad** [comment]
You need to mess with your config if you want it to activate at long distances... play with AimFieldOfView... Try increasing it to 50-60.

**Comment by d1monch1k** [comment]
Aim watches over the enemy, escorting him through the walls. And it would be nice that it would turn on when you press the shoot, and not constantly monitor the opponent

**Comment by Teklad** [comment]
This requires me to do BSP parsing or something else slightly more complicated.  I don't mind adding it when I find time.  In the mean time please use responsibly.

**Comment by Teklad** [comment]
Will be implementing BSP parsing as soon as I'm done with the offset dumper for Linux.  If @w3bn00b wants to he is more than welcome to get more PRs going since it'll likely take me another week to dig out the rest of the needed signatures for the dumper.

@w3bn00b just try to keep up with the same format for PRs as you used in your last one and I'll review and accept.  Sorry for my absence, I've been working a lot of overtime lately so haven't had much time for this.
